<?php

/**
 * PesageProducao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PesagemProducao extends BasePesagemProducao {

    var $idProperty = NULL; //NAO MODIFICAR ESTA PROPRIEDADE
    
    var $hasOne = NULL; //NAO MODIFICAR ESTA PROPRIEDADE
    
    var $hasMany = NULL; //NAO MODIFICAR ESTA PROPRIEDADE
    
    var $params = NULL; //NAO MODIFICAR ESTA PROPRIEDADE
    
    var $validationRule = NULL; //NAO MODIFICAR ESTA PROPRIEDADE

    var $modelBase = NULL; //NAO MODIFICAR ESTA PROPRIEDADE
    
    function __construct() {

        $this->idProperty = 'id_pesagem_producao';
        
        $this->hasOne = array(
            'Silo',
            'CaminhaoFrete',
            'Safra',
            'TabelaClassificacao'
        );
        
        $this->hasMany = array(
            'SafraTalhaoPesagemProducao'
            // 'UsuarioPerfil'
        );
        
        $this->params = array(
            /*array(
                'field' => '',
                'value' => ''
            )*/
        );
        
        $this->validationRule = array(
            'id_pesagem'                => 'requerido numerico',
            'id_silo'                   => 'requerido numerico',
            'id_safra'                  => 'requerido numerico',
            'id_caminhao_frete'         => 'requerido numerico',
            'id_tabela_classificacao'   => 'requerido numerico',
            'peso_bruto'                => 'tamanho_max[10]',
            'peso_tara'                 => 'tamanho_max[10]',
            'peso_total'                => 'tamanho_max[10]',
            'peso_umido'                => 'tamanho_max[10]',
            'peso_limpo'                => 'tamanho_max[10]',
            'peso_desconto'             => 'tamanho_max[10]',
            'umidade'                   => 'tamanho_max[10]',
            'perc_umidade'              => 'tamanho_max[10]',
            'impureza'                  => 'tamanho_max[10]',
            'perc_impureza'             => 'tamanho_max[10]',
            'verdes'                    => 'tamanho_max[10]',
            'perc_verdes'               => 'tamanho_max[10]',
            'partidos'                  => 'tamanho_max[10]',
            'perc_partidos'             => 'tamanho_max[10]',
            'ardidos'                   => 'tamanho_max[10]',
            'perc_ardidos'              => 'tamanho_max[10]',
            'picados'                   => 'tamanho_max[10]',
            'perc_picados'              => 'tamanho_max[10]',
            'avariados'                 => 'tamanho_max[10]',
            'perc_avariados'            => 'tamanho_max[10]'
        );
        
        //NAO MODIFICAR ESTE TRECHO DO CODIGO
        
        parent::__construct();
    }
    

}